apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cue
  namespace: cue
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: druzynada.example.com
      http:
        paths:
          # Jedna usługa obsługuje API, WebSocket i statyki
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  name: http
